# ----
# Site

title: CloudCannon Academy
url: "https://learn.cloudcannon.com"
google_analytics_key: "UA-37472773-1"
disqus_shortname: "learn-cloudcannon-com"
newsletter_action: "//cloudcannon.us12.list-manage.com/subscribe/post?u=c2598ec08fca5843b980a7d3f&amp;id=16297bb754"
theme: jekyll-theme-cloudcannon

active_sibling: Learn
main_url: https://cloudcannon.com

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: CloudCannon and Jekyll tutorials and resources
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: CloudCannon Academy
  links:
    - https://github.com/CloudCannon/academy

# -----
# Build

permalink: /jekyll/:title/

plugins:
  - jekyll-data
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:


jekyll-archives:
  enabled: ['tags']
  permalinks:
    tag: '/:name/'

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "tutorial"
      search_result_highlighting_selector: div.post
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

types:
  - Document
  - Video

_comments:
