source 'https://rubygems.org'

gem 'jekyll', '3.7.2'
gem 'jekyll-theme-cloudcannon', :github => 'CloudCannon/jekyll-theme-cloudcannon', :ref => '2540c'

group :jekyll_plugins do
	gem 'jekyll-archives'
	gem 'jekyll-paginate'
	gem 'jekyll-extract-element', '0.0.7'
	gem 'jekyll-shuffle', '0.0.2'
end