source 'https://rubygems.org'

gem 'jekyll', '4.1.1'
gem 'jekyll-theme-cloudcannon', :github => 'CloudCannon/jekyll-theme-cloudcannon', :branch => 'master'

group :jekyll_plugins do
	gem 'jekyll-archives'
	gem 'jekyll-paginate'
end